# https://taskfile.dev

version: '3'

interval: 500ms

tasks:
  default:
    cmds:
      - task -l
    silent: true
  run:
    watch: true
    sources:
      - '../mordor/**/*.js'
    cmds:
      - cmd: kill -9 $(lsof -ti:6473) 2>/dev/null
        ignore_error: true
        silent: true
      - bun start
    silent: true
  setup:
    desc: installs deps
    cmds:
      - bun install