# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task -l
    silent: true

  run:  
    desc: runs shire app 
    cmds:
      - bun dev
    silent: true

  setup:
    cmds:
      - bun install
    silent: true
